// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations/introspecção precisam de privilégios de DDL — usar a role dona das tabelas
    // (DIRECT_DATABASE_URL). DATABASE_URL em runtime aponta para a role restrita (sem BYPASSRLS).
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
